version: '3'

networks:
  php-blog:

services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql8-container
    environment:
      MYSQL_DATABASE: php_blog
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3305:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    networks:
      - php-blog
  php-service:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/php-blog"
    networks:
      - php-blog
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/php-blog"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-service
      - mysql-service
    networks:
      - php-blog