version: '3.9'

networks:
  php-blog:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/php-blog"
      - "./config/nginx/docker-compose.default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - composer
    networks:
      - php-blog
  mysql-service:
    image: percona
    container_name: mysql8-container
    environment: 
      MYSQL_DATABASE: php_blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
    ports: 
      - '3306:3306'
    restart: always # always restart unless stopped manually
    networks:
      - php-blog
  php-service:
    build:
      context: .
      dockerfile: ./config/php/Dockerfile
    hostname: php
    volumes:
      - "./:/var/www/php-blog"
    working_dir: "/var/www/php-blog/"
    ports:
      - "9000:9000"
    networks:
      - php-blog
    depends_on: 
      - mysql-service
  composer:
    image: composer:latest
    command: install --ignore-platform-reqs
    restart: "no"
    working_dir: "/var/www/php-blog/"
    depends_on: 
      - php-service
    volumes:
      - "./:/var/www/php-blog"