create table post
(
    post_id        int unsigned auto_increment
        primary key,
    title          varchar(255)  not null,
    url_key        varchar(255)  not null,
    image_path     varchar(255)  null,
    content        text          null,
    description    varchar(255)  null,
    published_date datetime      not null,
    category       int default 1 not null,
    author_id      int           not null,
    constraint url_key
        unique (url_key)
)
    charset = utf8;

INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (1, 'Hello World', 'hello-world', null, 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.', 'My first blog post', '2020-12-05 12:00:00', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (2, 'Fact that a reader', 'fact-that-a-reader', null, 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English.', 'It is a long established fact that a reader .', '2020-12-09 12:00:00', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (3, 'Many variations of passages', 'many-variations-of-passages', null, 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don''t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn''t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 'There are many variations of passages of Lorem Ipsum available', '2020-12-10 12:00:00', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (4, 'Test post', 'new-post', null, 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don''t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn''t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 'There are many variations of passages of Lorem Ipsum available', '2020-12-10 13:00:00', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (5, 'Test post 2', 'l2-post', null, 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don''t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn''t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 'There are many variations of passages of Lorem Ipsum available', '2020-12-10 15:00:00', 2, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (6, 'Test post 3', 'another-post', '/static/images/post_images/blog-1.jpg', 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don''t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn''t anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 'There are many variations of passages of Lorem Ipsum available', '2020-12-10 18:00:00', 2, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (7, 'title', '1', null, 'content', 'description', '2021-11-25 11:20:02', 2, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (10, 'title', 'url222ASD-key', null, 'content', 'description', '2021-11-25 11:28:33', 3, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (11, 'title', 'urlAAA', null, 'content', 'descr', '2021-11-25 11:29:11', 3, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (12, 'title', 'urlAAA2', null, 'content', 'descr', '2021-11-25 11:29:59', 4, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (13, 'title', 'urlAAA2вфыв', null, 'sdsdsd', 'adddvvrrr', '2021-11-25 11:31:11', 5, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (14, 'title', 'post-totl', null, 'sdsdsd', 'adddvvrrr', '2021-11-25 11:42:36', 5, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (15, 'title', 'post-totl2', null, 'content', 'descr', '2021-11-25 11:43:05', 6, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (16, 'post title', 'sample-125-key', null, 'post content', 'post description', '2021-11-25 11:55:20', 7, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (17, 'post title', 'asdfg-25455e', null, 'post conetnr', 'post description 2255444', '2021-11-25 12:07:57', 8, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (18, 'food psot', 'food-post', null, 'food psot content', 'food psot description', '2021-11-26 02:14:38', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (19, 'food post with category', 'food-post-with-category', null, 'food post with category content', 'food post with category title', '2021-11-26 02:18:09', 3, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (20, 'undef', 'undef', null, 'undef', 'undef', '2021-12-03 11:48:07', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (21, 'undef2', 'undef2', null, 'undef undef', 'undef2', '2021-12-03 11:48:21', 1, 0);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (22, 'dfdfdw', 'sdfsdfsdfsdfsdfffffeewwq', '/static/images/post_images/22', 'fdfdfsdfw', 'fsdfsdfw', '2022-06-10 11:20:48', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (23, 'fff', 'sdfsdfsdf', 'static/images/post_images/23', 'sdfs', 'sdfsdf', '2022-06-10 11:35:13', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (24, 'sdfsdf', 'ggwssd', null, 'sdfsdfsd', 'fsdfsdfsd', '2022-06-10 11:39:46', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (25, 'sdfsdf', 'ggwssds', null, 'sdfsdfsd', 'fsdfsdfsd', '2022-06-10 11:40:28', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (26, 'asdas', 'eeee', 'static/images/post_images/26.png', 'asdasd', 'dddd', '2022-06-10 11:52:35', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (27, 'sds', 'wwww', 'static/images/post_images/27.png', 'wwww', 'dddd', '2022-06-10 11:54:08', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (28, 'dfdfsdf', 'rrrr', 'static/images/post_images/28.png', 'gggs', 'fdgdfgdfg', '2022-06-10 11:58:29', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (29, 'jpg to png', 'ssjpgtopng', '', 'jpg to png', 'jpg to png', '2022-06-10 12:00:48', 6, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (30, 'danis', 'daniskakawka', 'static/images/post_images/30.png', 'kakawka', 'danis kakawka', '2022-06-10 12:09:54', 1, 4);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (31, 'TET-a-TET', 'thought', 'static/images/post_images/31.png', 'tref', 'href', '2022-06-10 12:12:11', 2, 5);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (32, 'without image', 'without-image', null, 'without image', 'without image', '2022-06-10 12:23:55', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (33, 'with image', 'with-image', 'static/images/post_images/33.png', 'with image', 'with image', '2022-06-10 12:24:14', 2, 1);
INSERT INTO php_blog.post (post_id, title, url_key, image_path, content, description, published_date, category, author_id) VALUES (34, 'qwww', 'eeqq', null, 'eeqq', 'qqwwe', '2022-06-10 12:25:03', 2, 5);